# Generated by Django 3.2.8 on 2021-10-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='estado',
            field=models.CharField(choices=[('activa', 'activa'), ('finalizada', 'finalizada')], default='activa', max_length=50),
        ),
    ]
