# Generated by Django 3.2.8 on 2021-10-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='tipo',
            field=models.CharField(choices=[('Preguntar', 'Preguntar'), ('Acusar', 'Acusar')], max_length=20),
        ),
    ]
